# -*- coding: utf-8 -*-
"""Copy of ModelTraining_GroupB10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17tjGhJmj7P30q16F0Tfcp0_3IEPyzmul
"""

#Importing pandas library
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
import numpy as np
from sklearn.utils.class_weight import compute_class_weight
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping
import tensorflow as tf
import random
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report
from sklearn.tree import plot_tree

from google.colab import drive
drive.mount('/content/drive')

np.random.seed(42)
random.seed(42)

#Loading data into a DataFrame
train_data_frame = pd.read_csv("/content/Hotel-A-train.csv")
validation_data_frame=pd.read_csv("/content/Hotel-A-validation.csv")

# Removing variables that will not be needed
train_data_frame = train_data_frame.drop(['Reservation-id', 'Expected_checkout','Expected_checkin', "Booking_date"], axis=1)
validation_data_frame = validation_data_frame.drop(['Reservation-id', 'Expected_checkout','Expected_checkin', "Booking_date"], axis=1)

# Creating a new variable and deleting the previous variables used to make it
train_data_frame['Total_Guests'] = (
    train_data_frame['Adults'] +
    train_data_frame['Children'] +
    train_data_frame['Babies'])
train_data_frame.drop(columns=['Adults', 'Children', 'Babies'], inplace=True)

# Creating a new variable and deleting the previous variables used to make it
validation_data_frame['Total_Guests'] = (
    validation_data_frame['Adults'] +
    validation_data_frame['Children'] +
    validation_data_frame['Babies'])
validation_data_frame.drop(columns=['Adults', 'Children', 'Babies'], inplace=True)

train_data_frame['Reservation_Status'] = train_data_frame['Reservation_Status'].replace('Check-In', 'Check-Out')
train_data_frame['Reservation_Status'] = train_data_frame['Reservation_Status'].str.lower()

validation_data_frame['Reservation_Status'] = validation_data_frame['Reservation_Status'].replace('Check-In', 'Check-Out')
validation_data_frame['Reservation_Status'] = validation_data_frame['Reservation_Status'].str.lower()

train_data_frame.info()

print(train_data_frame['Reservation_Status'].unique())

validation_data_frame.info()

print(validation_data_frame['Reservation_Status'].unique())

# #Loading data into a DataFrame
# train_data_frame = pd.read_csv("/content/Cleanedtrain_df.csv")
# validation_data_frame =pd.read_csv("/content/cleanedval_df.csv")

from sklearn.model_selection import train_test_split

# Combine the train and validation dataframes
combined_data = pd.concat([train_data_frame, validation_data_frame], ignore_index=True)

# Define the target variable
target = "Reservation_Status"

# Separate features (X) and target (y)
X = combined_data.drop(columns=[target])
y = combined_data[target]

# Perform an 80-20 train-test split
X_train, X_validation, y_train, y_validation = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

print("Combined dataset shape:", combined_data.shape)
print("New X_train shape:", X_train.shape)
print("New X_validation shape:", X_validation.shape)
print("New y_train shape:", y_train.shape)
print("New y_validation shape:", y_validation.shape)

# #Defining the target variable
# target = "Reservation_Status"

# # Training data
# X_train = train_data_frame.drop(columns=[target])
# y_train = train_data_frame[target]

# # Validation data
# X_validation = validation_data_frame.drop(columns=[target])
# y_validation = validation_data_frame[target]

X_train = pd.get_dummies(X_train)
X_validation = pd.get_dummies(X_validation)

X_validation = X_validation.reindex(columns=X_train.columns, fill_value=0)

# Encode target labels
le = LabelEncoder()
y_train = le.fit_transform(y_train)
y_validation = le.transform(y_validation)

# # Label encoding categorical variables
# categorical_cols = train_data_frame.select_dtypes(include=['object']).columns
# label_encoders = {}

# for col in categorical_cols:
#     le = LabelEncoder()
#     train_data_frame[col] = le.fit_transform(train_data_frame[col].astype(str))
#     validation_data_frame[col] = le.fit_transform(validation_data_frame[col].astype(str))
#     label_encoders[col] = le

y_train_cat = to_categorical(y_train)
y_validation_cat = to_categorical(y_validation)

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_validation = scaler.transform(X_validation)

print("Train Size:", X_train.shape)
print("Validation Size:", X_validation.shape)
total_size = X_train.shape[0] + X_validation.shape[0]
print("Train Split:", X_train.shape[0]/total_size*100)
print("Validation Split:", X_validation.shape[0]/total_size*100)

"""# **Model Building**

## **Decision Tree**
"""

# Create model
dt_model = DecisionTreeClassifier(
    max_depth=5,           # control overfitting
    min_samples_split=10,  # avoid too small splits
    random_state=42
)

# Train model
dt_model.fit(X_train, y_train)

# Predict
y_pred = dt_model.predict(X_validation)

# Evaluate
print(classification_report(y_validation, y_pred))

"""## **Model I - Weighted Cross Entropy + Neural Network**"""

# Compute class weights to handle imbalance
class_weights = compute_class_weight(
    class_weight='balanced',
    classes=np.unique(y_train),
    y=y_train
)

class_weights_dict = dict(enumerate(class_weights))

class_weights_dict

import tensorflow as tf

def focal_loss(gamma=2., alpha=.25):
    def loss(y_true, y_pred):
        ce = tf.keras.losses.categorical_crossentropy(y_true, y_pred)
        pt = tf.exp(-ce)
        return alpha * (1 - pt) ** gamma * ce
    return loss

def f1_macro(y_true, y_pred):
    y_pred_labels = tf.argmax(y_pred, axis=1)
    y_true_labels = tf.argmax(y_true, axis=1)

    # True positives, predicted positives, actual positives
    tp = tf.math.count_nonzero(y_pred_labels * y_true_labels, dtype=tf.float32)
    predicted_positives = tf.math.count_nonzero(y_pred_labels, dtype=tf.float32)
    actual_positives = tf.math.count_nonzero(y_true_labels, dtype=tf.float32)

    precision = tp / (predicted_positives + 1e-8)
    recall = tp / (actual_positives + 1e-8)
    f1 = 2 * (precision * recall) / (precision + recall + 1e-8)
    return f1

selected_loss =  f1_macro
loss_metric = 'categorical_crossentropy'

model = Sequential([
    Dense(256, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(128, activation='relu'),
    Dense(64, activation='relu'),
    Dense(32, activation='relu'),
    Dense(3, activation='softmax')
])

# Compile model with categorical cross entropy
model.compile(
    optimizer=Adam(learning_rate=0.00001),
    loss= loss_metric,
    metrics=[selected_loss]
)

from tensorflow.keras.callbacks import ModelCheckpoint

# Create early stopping callback
early_stop = EarlyStopping(
    monitor='val_f1_macro',          # monitor validation loss
    patience=10,                  # number of epochs to wait before stopping
    mode="max",                 # maximize validation loss to find the best model
    restore_best_weights=True    # restore the best model weights
)

checkpoint = ModelCheckpoint(
    'best_model01.h5',        # file where the best model will be saved
    monitor='val_f1_macro',     # metric to monitor
    save_best_only=True,    # only save when validation improves
    mode='max',             # lower validation loss is better
    verbose=1
)

# Train the model with class weights
history = model.fit(
    X_train,
    y_train_cat,
    validation_data=(X_validation, y_validation_cat),
    epochs=100,
    batch_size=64,
    class_weight=class_weights_dict,
    callbacks=[checkpoint]
)

# Plot accuracy curves
plt.plot(history.history['f1_macro'], label='Train F1 Score')
plt.plot(history.history['val_f1_macro'], label='Validation F1 Score')

plt.title('Model F1 Score During Training')
plt.xlabel('Epochs')
plt.ylabel('F1 Score')
plt.legend()
plt.show()

from tensorflow.keras.models import load_model

best_model = load_model("best_model01.h5", custom_objects={"f1_macro": f1_macro})

y_pred = best_model.predict(X_validation)

y_pred_classes = np.argmax(y_pred, axis=1)
y_true = np.argmax(y_validation_cat, axis=1)

comparison = pd.DataFrame({
    "Actual": y_true,
    "Predicted": np.argmax(y_pred, axis=1),
    "Probability": np.max(y_pred, axis=1)
})

print(comparison.head(10))

from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_true, y_pred_classes)
print(cm)

import seaborn as sns
import matplotlib.pyplot as plt

class_names = ["Check-In", "Cancelled", "No-Show"]

plt.figure(figsize=(6,5))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=class_names,
            yticklabels=class_names)

plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
plt.show()

from sklearn.metrics import classification_report

y_pred_probs = model.predict(X_validation)
# y_pred = np.argmax(y_pred_classes, axis=1)

print("\n--- Final Validation Report ---")
print(classification_report(y_validation, y_pred_classes, target_names=['check-in', 'cancelation', 'no-show']))

"""## **Model II - SMOTE + Neural Network**"""

from imblearn.over_sampling import SMOTE
from collections import Counter

# Before SMOTE
print("Before SMOTE:", Counter(y_train))

# Apply SMOTE
smote = SMOTE(random_state=42)
X_train_resampled, y_train_resampled = smote.fit_resample(X_train, y_train)

# After SMOTE
print("After SMOTE:", Counter(y_train_resampled))

model = Sequential([
    Dense(256, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(128, activation='relu'),
    Dense(64, activation='relu'),
    # Dense(32, activation='relu'),
    Dense(3, activation='softmax')
])

# Compile model with categorical cross entropy
model.compile(
    optimizer=Adam(learning_rate=0.0001),
    loss=loss_metric,
    metrics=[selected_loss]
)

checkpoint = ModelCheckpoint(
    'best_model02.h5',        # file where the best model will be saved
    monitor='val_f1_macro',     # metric to monitor
    save_best_only=True,    # only save when validation improves
    mode='max',             # lower validation loss is better
    verbose=1
)

y_train_cat = to_categorical(y_train_resampled)

# Train the model with class weights
history = model.fit(
    X_train_resampled,
    y_train_cat,
    validation_data=(X_validation, y_validation_cat),
    epochs=100,
    batch_size=64,
    callbacks=[checkpoint]
)

# Plot accuracy curves
plt.plot(history.history['f1_macro'], label='Train F1 Score')
plt.plot(history.history['val_f1_macro'], label='Validation F1 Score')

plt.title('Model F1 Score During Training')
plt.xlabel('Epochs')
plt.ylabel('F1 Score')
plt.legend()
plt.show()

best_model = load_model("best_model02.h5", custom_objects={"f1_macro": f1_macro})
y_pred = best_model.predict(X_validation)

y_pred_classes = np.argmax(y_pred, axis=1)
y_true = np.argmax(y_validation_cat, axis=1)

comparison = pd.DataFrame({
    "Actual": y_true,
    "Predicted": np.argmax(y_pred, axis=1),
    "Probability": np.max(y_pred, axis=1)
})

print(comparison.head(10))

cm = confusion_matrix(y_true, y_pred_classes)

class_names = ["Check-In", "Cancelled", "No-Show"]

plt.figure(figsize=(6,5))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=class_names,
            yticklabels=class_names)

plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
plt.show()

y_pred_probs = model.predict(X_validation)
# y_pred = np.argmax(y_pred_classes, axis=1)

print("\n--- Final Validation Report ---")
print(classification_report(y_validation, y_pred_classes, target_names=['check-in', 'cancelation', 'no-show']))

"""## **Model III - Hybrid of the above two**"""

model = Sequential([
    Dense(256, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(128, activation='relu'),
    Dense(64, activation='relu'),
    # Dense(32, activation='relu'),
    Dense(3, activation='softmax')
])

# Compile model with categorical cross entropy
model.compile(
    optimizer=Adam(learning_rate=0.0001),
    loss=loss_metric,
    metrics=[selected_loss]
)

checkpoint = ModelCheckpoint(
    'best_model03.h5',        # file where the best model will be saved
    monitor='val_f1_macro',     # metric to monitor
    save_best_only=True,    # only save when validation improves
    mode='max',             # lower validation loss is better
    verbose=1
)

class_weights_dict

new_class_weights = {
    0: np.float64(0.35),
    1: np.float64(0.3),
    2: np.float64(0.35)
}

# Train the model with class weights
history = model.fit(
    X_train_resampled,
    y_train_cat,
    validation_data=(X_validation, y_validation_cat),
    epochs=150,
    batch_size=64,
    callbacks=[checkpoint],
    class_weight=new_class_weights
)

# Plot accuracy curves
plt.plot(history.history['f1_macro'], label='Train F1 Score')
plt.plot(history.history['val_f1_macro'], label='Validation F1 Score')

plt.title('Model F1 Score During Training')
plt.xlabel('Epochs')
plt.ylabel('F1 Score')
plt.legend()
plt.show()

best_model = load_model("best_model03.h5", custom_objects={"f1_macro": f1_macro})
y_pred = best_model.predict(X_validation)

y_pred_classes = np.argmax(y_pred, axis=1)
y_true = np.argmax(y_validation_cat, axis=1)

comparison = pd.DataFrame({
    "Actual": y_true,
    "Predicted": np.argmax(y_pred, axis=1),
    "Probability": np.max(y_pred, axis=1)
})

print(comparison.head(10))

cm = confusion_matrix(y_true, y_pred_classes)

class_names = ["Check-In", "Cancelled", "No-Show"]

plt.figure(figsize=(6,5))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=class_names,
            yticklabels=class_names)

plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
plt.show()

y_pred_probs = model.predict(X_validation)
# y_pred = np.argmax(y_pred_classes, axis=1)

print("\n--- Final Validation Report ---")
print(classification_report(y_validation, y_pred_classes, target_names=['check-in', 'cancelation', 'no-show']))

"""## **Decision Tree + SMOTE**"""

# Create model
dt_model = DecisionTreeClassifier(
    max_depth=5,           # control overfitting
    min_samples_split=10,  # avoid too small splits
    random_state=42
)

# Train model
dt_model.fit(X_train_resampled, y_train_cat)

# Predict
y_pred = dt_model.predict(X_validation)

# Evaluate
print(classification_report(y_validation_cat, y_pred))

