# -*- coding: utf-8 -*-
"""EDA_files_Train_GroupB10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12EgKg9D4TwFiHZUVF6tzQ4PFYiKHWoJ1
"""

#Importing pandas library
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder

#Loading data into a DataFrame
data_frame = pd.read_csv("data/Hotel-A-train.csv")

"""Importing required libraries for data handling data visualization
and preprocessing tasks and Reading the Hotel-A validation dataset from Google Drive and storing it in a DataFrame for exploratory data analysis and model validation

# Data Inspection
"""

#displaying first five rows
data_frame.head()

""" Inspecting the first five rows to understand the structure of the dataset"""

data_frame.shape

"""Checking dataset dimensions to understand the scale of the data"""

# Program to print all the column names of the data_frame
list(data_frame.columns)

"""identifying the variables present in the dataset"""

data_frame.info()

"""identify variable types, and verify successful data loading

##Missing Values
"""

data_frame.isnull().sum()

# Percentage of missing values for each column
missing_percentage = data_frame.isnull().mean() * 100

# Display results
missing_percentage

"""Computing the proportion (in percentage) of missing values for each variable to evaluate the extent of missing data before preprocessing."""

data_frame.describe()

categorical_df = data_frame.select_dtypes(include=['object', 'category'])

categorical_df.describe()

"""Understanding the categorical variables"""

# Removing variables that will not be needed
data_frame = data_frame.drop(['Reservation-id', 'Expected_checkout','Expected_checkin', "Booking_date"], axis=1)

"""Removing variables that are not relevant to predicting reservation status.
The variables Reservation id, Expected_checkin, Expected_checkout, and Booking_date were removed from the dataset as they do not directly contribute to predicting reservation status. Reservation id is a unique identifier and carries no analytical value. The date related variables were excluded because, in their raw format, they do not provide meaningful predictive insight and may introduce noise into the model. From a real world hotel management perspective, the objective is to identify behavioural and customer related factors that influence cancellations or no shows, rather than relying on identification fields or unprocessed date values.
"""

# Finding unique values of each categorical variable
# Selecting categorical columns
categorical_cols = data_frame.select_dtypes(include=['object']).columns
print("Categorical columns:", categorical_cols)
# Listing unique values for each Categorical column
for col in categorical_cols:
    print(f"Unique values in '{col}':")
    print(data_frame[col].unique())
    print("-" * 40)

"""Identifying categorical variables in the dataset and examining their unique values to understand the structure of each feature and detect inconsistencies"""

data_frame['Reservation_Status'] = data_frame['Reservation_Status'].str.lower()

"""During the exploration of categorical variables, an inconsistency was identified in the Reservation_Status column, where both “Check-Out” and “Check-out” appeared as separate categories due to differences in capitalisation. Although they represent the same outcome, the model would treat them as distinct classes, potentially distorting class distributions and reducing predictive accuracy. To address this issue, all values in the column were standardised by converting them to lowercase."""

# Finding unique values of each categorical variable
# Selecting categorical columns
categorical_cols = data_frame.select_dtypes(include=['object']).columns
print("Categorical columns:", categorical_cols)
# Listing unique values for each Categorical column
for col in categorical_cols:
    print(f"Unique values in '{col}':")
    print(data_frame[col].unique())
    print("-" * 40)

"""Confirming if the correction has been resolved correctly

##Handling Outliers
"""

#Detecting outliers using the IQR method for numerical features
  # Step 01:Select numerical columns
numerical_cols = data_frame.select_dtypes(include=['int64', 'float64']).columns
  # Step 02:Creating Dictionary to store outlier indices for each column
outliers_dict = {}

for col in numerical_cols:
    Q1 = data_frame[col].quantile(0.25)
    Q3 = data_frame[col].quantile(0.75)
    IQR = Q3 - Q1

    # Defining lower and upper bounds
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    # Finding outlier indices
    outlier_indices = data_frame[(data_frame[col] < lower_bound) | (data_frame[col] > upper_bound)].index
    outliers_dict[col] = outlier_indices

  # Step 03:Display number of outliers per numerical column
for col, indices in outliers_dict.items():
    print(f"{col}: {len(indices)} outliers")


#Visualizing the outliers per variable for better understanding
for col in numerical_cols:
  plt.figure(figsize=(8, 4))
  sns.boxplot(x=data_frame[col])
  plt.title(f'Boxplot of {col} showing potential outliers')
  plt.show()

"""Although the variable Adults contained a large number of statistical outliers, these values represent valid booking sizes rather than data errors. Therefore, instead of removing observations, the variable was transformed into grouped categories to preserve behavioural information while reducing the influence of extreme values.

## Feature Engineering
"""

# Creating a new variable and deleting the previous variables used to make it
data_frame['Total_Guests'] = (
    data_frame['Adults'] +
    data_frame['Children'] +
    data_frame['Babies'])
data_frame.drop(columns=['Adults', 'Children', 'Babies'], inplace=True)

#Visualizing the new variable
plt.figure(figsize=(6,4))
plt.hist(data_frame['Total_Guests'], bins=range(1, data_frame['Total_Guests'].max()+2))
plt.title("Distribution of Total Guests per Reservation")
plt.xlabel("Total Guests")
plt.ylabel("Number of Reservations")
plt.show()

"""Creating a new feature 'Total_Guests' by summing 'Adults', 'Children', and 'Babies' to capture the total number of guests in a booking. The original individual columns are then removed to reduce redundancy and simplify the dataset for modelling.

## Encoding
"""

# Label encoding categorical variables
categorical_cols = data_frame.select_dtypes(include=['object']).columns
label_encoders = {}

for col in categorical_cols:
    le = LabelEncoder()
    data_frame[col] = le.fit_transform(data_frame[col].astype(str))
    label_encoders[col] = le

"""Converting all categorical variables into numeric form using Label Encoding, which is required for machine learning algorithms that cannot handle text data directly. Each categorical column is transformed and the corresponding LabelEncoder is stored for future use.

#Exploratory data analysis

##Target Variable Analysis

Count Plot (Class Balance Check)
"""

plt.figure(figsize=(6,4))
sns.countplot(x='Reservation_Status', data=data_frame)
plt.title('Target Variable Distribution')
plt.xlabel('Reservation Status')
plt.ylabel('Count')
plt.show()

# Print class percentages
print(data_frame['Reservation_Status'].value_counts(normalize=True) * 100)

"""Visualising the distribution of the target variable 'Reservation_Status' using a count plot to understand class imbalance and the relative frequency of each outcome. The results show that the majority of reservations (77%) are check-outs (class 1), while cancellations (15%) and no-shows (8%) are less frequent, indicating class imbalance.

## Univariate Analysis

Numerical Variables
"""

numerical_cols = data_frame.select_dtypes(include=['int64','float64']).columns

for col in numerical_cols:
    plt.figure(figsize=(6,4))
    sns.histplot(data_frame[col], kde=True)
    plt.title(f'Distribution of {col}')
    plt.show()

"""Visualising the distribution of all numeric variables in the dataset using histograms with KDE (kernel density estimates). This helps identify patterns such as skewness, outliers, or unusual distributions, which may inform feature scaling, transformation, or further preprocessing.

## Bivariate Analysis

numerical variables
"""

for col in numerical_cols:
    plt.figure(figsize=(6,4))
    sns.boxplot(x='Reservation_Status', y=col, data=data_frame)
    plt.title(f'{col} vs Reservation Status')
    plt.show()

"""Creating boxplots of each numeric variable against the target variable 'Reservation_Status'. This helps visualise how the distribution of numeric features differs across reservation outcomes, highlighting trends, differences, and potential predictors for the model.

##Correlation Analysis
"""

#Correlation heat map
# Step 01: Select numeric columns only
numeric_df = data_frame.select_dtypes(include=['int64', 'float64'])

# Step 02: Calculate correlation matrix
corr_matrix = numeric_df.corr()

# Step 03:  Plot heatmap
plt.figure(figsize=(10,8))
sns.heatmap(corr_matrix, annot=True, fmt=".2f", cmap="coolwarm")
plt.title("Correlation Matrix")
plt.show()

"""Selecting numeric columns and calculating the correlation matrix to examine
linear relationships between all numeric features. A heatmap is plotted to visualise the strength and direction of these correlations, which can inform feature selection, multicollinearity checks and model interpretation. For example, in the hotel reservation dataset, Use_Promotion and Discount_Rate show a strong positive correlation (0.64), suggesting that promotions are closely linked to discounts.
"""

